# Generated by Django 4.2.20 on 2025-06-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_task_delete_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("day_1", models.BooleanField(default=False)),
                ("day_3", models.BooleanField(default=False)),
                ("day_5", models.BooleanField(default=False)),
                ("day_7", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
