# Generated by Django 4.2.20 on 2025-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_problemrevision_delete_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemrevision",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="problemrevision",
            name="link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="problemrevision",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
