# Generated by Django 4.2.20 on 2025-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_problemrevision_difficulty_problemrevision_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemrevision",
            name="link",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
