# Generated by Django 4.2.20 on 2025-06-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_problemrevision_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemrevision",
            name="link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
